<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->report_type }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #1a56db; border-bottom: 3px solid #1a56db; padding-bottom: 10px; }
        .meta { color: #666; margin-bottom: 20px; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #1a56db; color: white; padding: 10px; text-align: left; }
        td { padding: 8px 10px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .summary { background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .summary-item { display: inline-block; margin-right: 30px; margin-bottom: 5px; }
        .summary-label { font-weight: bold; color: #666; }
        .summary-value { font-size: 18px; font-weight: bold; color: #1a56db; }
        .footer { margin-top: 30px; color: #666; font-size: 12px; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>{{ $report->report_type }}</h1>
    <div class="meta">
        Generated: {{ $generated_at }}<br>
        @if($report->grade_level) Grade Level: {{ $report->grade_level }} @endif
        @if($report->trimester) Trimester: {{ $report->trimester }} @endif
    </div>

    @if(!empty($summary))
        <h2>Summary</h2>
        <div class="summary">
            @foreach($summary as $key => $value)
                <div class="summary-item">
                    <div class="summary-label">{{ str_replace('_', ' ', ucwords($key)) }}</div>
                    <div class="summary-value">{{ $value }}</div>
                </div>
            @endforeach
        </div>
    @endif

    @if(!empty($data) && !empty($headers))
        <h2>Data</h2>
        <table>
            <thead>
                <tr>
                    @foreach($headers as $header)
                        <th>{{ str_replace('_', ' ', ucwords($header)) }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($data as $row)
                    <tr>
                        @foreach($headers as $header)
                            <td>{{ $row[$header] ?? '' }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>No detailed data rows available.</p>
    @endif

    <div class="footer">Generated by StudyNest - Learning Management System</div>
</body>
</html>
