// Static content for every interactive game.
// KEYS MUST MATCH the game_title strings used in
// app/Http/Controllers/Teacher/GameController.php EXACTLY.
//
// Every game below now has 20 rounds/items, ordered from easiest
// to hardest, appropriate for Key Stage 2 (Grades 4-6).

const gameDefinitions = {
    // ===== GRADE 4 =====
    'Word Builder': {
        grade: 'Grade 4',
        type: 'literacy',
        description: 'Drag the letters into the blanks to spell the word shown by the picture.',
        content: {
            rounds: [
                { image: '🐱', word: 'CAT', letters: ['C', 'A', 'T', 'X', 'B'] },
                { image: '🐶', word: 'DOG', letters: ['D', 'O', 'G', 'P', 'N'] },
                { image: '🌞', word: 'SUN', letters: ['S', 'U', 'N', 'M', 'Y'] },
                { image: '🐷', word: 'PIG', letters: ['P', 'I', 'G', 'D', 'T'] },
                { image: '🐝', word: 'BEE', letters: ['B', 'E', 'E', 'R', 'L'] },
                { image: '🐟', word: 'FISH', letters: ['F', 'I', 'S', 'H', 'K', 'W'] },
                { image: '🐸', word: 'FROG', letters: ['F', 'R', 'O', 'G', 'S', 'L'] },
                { image: '🦆', word: 'DUCK', letters: ['D', 'U', 'C', 'K', 'B', 'T'] },
                { image: '🐻', word: 'BEAR', letters: ['B', 'E', 'A', 'R', 'S', 'N'] },
                { image: '🦁', word: 'LION', letters: ['L', 'I', 'O', 'N', 'T', 'M'] },
                { image: '🐐', word: 'GOAT', letters: ['G', 'O', 'A', 'T', 'S', 'B'] },
                { image: '🦀', word: 'CRAB', letters: ['C', 'R', 'A', 'B', 'T', 'N'] },
                { image: '🐴', word: 'HORSE', letters: ['H', 'O', 'R', 'S', 'E', 'T', 'P'] },
                { image: '🍎', word: 'APPLE', letters: ['A', 'P', 'P', 'L', 'E', 'S', 'T'] },
                { image: '🍇', word: 'GRAPE', letters: ['G', 'R', 'A', 'P', 'E', 'T', 'N'] },
                { image: '🐯', word: 'TIGER', letters: ['T', 'I', 'G', 'E', 'R', 'S', 'B'] },
                { image: '🦓', word: 'ZEBRA', letters: ['Z', 'E', 'B', 'R', 'A', 'T', 'N'] },
                { image: '🐋', word: 'WHALE', letters: ['W', 'H', 'A', 'L', 'E', 'T', 'S'] },
                { image: '🐒', word: 'MONKEY', letters: ['M', 'O', 'N', 'K', 'E', 'Y', 'T', 'S'] },
                { image: '🐬', word: 'DOLPHIN', letters: ['D', 'O', 'L', 'P', 'H', 'I', 'N', 'T', 'S'] },
            ],
        },
    },

    'Sentence Scramble': {
        grade: 'Grade 4',
        type: 'literacy',
        description: 'Drag the words into the correct order to form a proper sentence.',
        content: {
            rounds: [
                { correct: ['The', 'cat', 'is', 'sleeping'], scrambled: ['sleeping', 'The', 'cat', 'is'] },
                { correct: ['We', 'play', 'in', 'the', 'park'], scrambled: ['park', 'We', 'the', 'in', 'play'] },
                { correct: ['I', 'like', 'to', 'read', 'books'], scrambled: ['read', 'I', 'books', 'to', 'like'] },
                { correct: ['She', 'sings', 'a', 'happy', 'song'], scrambled: ['a', 'song', 'She', 'happy', 'sings'] },
                { correct: ['The', 'sun', 'is', 'very', 'bright'], scrambled: ['very', 'The', 'bright', 'sun', 'is'] },
                { correct: ['My', 'dog', 'loves', 'to', 'run'], scrambled: ['to', 'My', 'run', 'dog', 'loves'] },
                { correct: ['He', 'eats', 'breakfast', 'every', 'morning'], scrambled: ['every', 'He', 'morning', 'eats', 'breakfast'] },
                { correct: ['They', 'walk', 'to', 'school', 'together'], scrambled: ['school', 'They', 'together', 'walk', 'to'] },
                { correct: ['We', 'watch', 'movies', 'on', 'weekends'], scrambled: ['on', 'We', 'weekends', 'watch', 'movies'] },
                { correct: ['The', 'bird', 'flies', 'over', 'the', 'tree'], scrambled: ['over', 'The', 'tree', 'bird', 'the', 'flies'] },
                { correct: ['The', 'children', 'play', 'in', 'the', 'garden'], scrambled: ['in', 'The', 'garden', 'children', 'the', 'play'] },
                { correct: ['She', 'reads', 'a', 'book', 'before', 'bed'], scrambled: ['before', 'She', 'bed', 'reads', 'a', 'book'] },
                { correct: ['My', 'family', 'enjoys', 'eating', 'dinner', 'together'], scrambled: ['dinner', 'My', 'together', 'family', 'enjoys', 'eating'] },
                { correct: ['The', 'teacher', 'explains', 'the', 'lesson', 'clearly'], scrambled: ['clearly', 'The', 'lesson', 'teacher', 'explains', 'the'] },
                { correct: ['He', 'rides', 'his', 'bicycle', 'to', 'the', 'park'], scrambled: ['to', 'He', 'park', 'rides', 'the', 'his', 'bicycle'] },
                { correct: ['The', 'rain', 'fell', 'softly', 'on', 'the', 'roof'], scrambled: ['on', 'The', 'roof', 'fell', 'the', 'rain', 'softly'] },
                { correct: ['We', 'planted', 'flowers', 'in', 'our', 'garden', 'yesterday'], scrambled: ['yesterday', 'We', 'garden', 'planted', 'our', 'in', 'flowers'] },
                { correct: ['The', 'students', 'listened', 'carefully', 'to', 'the', 'story'], scrambled: ['to', 'The', 'story', 'listened', 'the', 'students', 'carefully'] },
                { correct: ['My', 'best', 'friend', 'and', 'I', 'love', 'drawing'], scrambled: ['love', 'My', 'drawing', 'best', 'I', 'friend', 'and'] },
                { correct: ['The', 'farmer', 'feeds', 'the', 'animals', 'every', 'morning'], scrambled: ['every', 'The', 'morning', 'feeds', 'the', 'farmer', 'animals'] },
            ],
        },
    },

    'Balloon Pop Math': {
        grade: 'Grade 4',
        type: 'numeracy',
        description: 'Tap only the balloons that equal the target number before time runs out.',
        content: {
            rounds: [
                { target: 5, numbers: [5, 3, 5, 7, 2, 5, 8, 4] },
                { target: 8, numbers: [8, 3, 8, 5, 6, 8, 2, 7] },
                { target: 6, numbers: [6, 9, 3, 6, 7, 6, 1, 8] },
                { target: 10, numbers: [10, 4, 10, 7, 3, 10, 6, 9] },
                { target: 7, numbers: [7, 2, 7, 9, 4, 7, 3, 8] },
                { target: 9, numbers: [9, 4, 9, 6, 2, 9, 7, 5] },
                { target: 12, numbers: [5, 12, 9, 12, 4, 10, 12, 6] },
                { target: 11, numbers: [11, 3, 11, 7, 5, 11, 9, 2] },
                { target: 13, numbers: [13, 5, 13, 8, 4, 13, 10, 6] },
                { target: 14, numbers: [14, 6, 14, 9, 3, 14, 11, 7] },
                { target: 15, numbers: [15, 8, 15, 10, 6, 15, 12, 9] },
                { target: 16, numbers: [16, 7, 16, 10, 5, 16, 12, 9] },
                { target: 17, numbers: [17, 8, 17, 11, 6, 17, 13, 9] },
                { target: 18, numbers: [18, 9, 18, 12, 6, 18, 14, 10] },
                { target: 19, numbers: [19, 9, 19, 13, 7, 19, 15, 10] },
                { target: 20, numbers: [20, 10, 20, 15, 8, 20, 17, 12] },
                { target: 21, numbers: [21, 10, 21, 14, 7, 21, 17, 11] },
                { target: 22, numbers: [22, 11, 22, 15, 8, 22, 17, 12] },
                { target: 24, numbers: [24, 12, 24, 16, 8, 24, 19, 13] },
                { target: 25, numbers: [25, 13, 25, 18, 9, 25, 20, 15] },
            ],
        },
    },

    'Sorting Baskets': {
        grade: 'Grade 4',
        type: 'numeracy',
        description: 'Drag each number into the correct basket: Even or Odd.',
        content: {
            rounds: [
                {
                    basketA: 'Even',
                    basketB: 'Odd',
                    items: [
                        { value: 4, type: 'Even' },
                        { value: 7, type: 'Odd' },
                        { value: 10, type: 'Even' },
                        { value: 3, type: 'Odd' },
                        { value: 8, type: 'Even' },
                        { value: 5, type: 'Odd' },
                        { value: 12, type: 'Even' },
                        { value: 9, type: 'Odd' },
                        { value: 15, type: 'Odd' },
                        { value: 18, type: 'Even' },
                        { value: 21, type: 'Odd' },
                        { value: 24, type: 'Even' },
                        { value: 27, type: 'Odd' },
                        { value: 30, type: 'Even' },
                        { value: 33, type: 'Odd' },
                        { value: 36, type: 'Even' },
                        { value: 39, type: 'Odd' },
                        { value: 42, type: 'Even' },
                        { value: 45, type: 'Odd' },
                        { value: 50, type: 'Even' },
                    ],
                },
            ],
        },
    },

    // ===== GRADE 5 =====
    'Match the Meaning': {
        grade: 'Grade 5',
        type: 'literacy',
        description: 'Drag each word on the left to its matching synonym on the right.',
        content: {
            pairs: [
                { word: 'Happy', match: 'Joyful' },
                { word: 'Big', match: 'Large' },
                { word: 'Fast', match: 'Quick' },
                { word: 'Sad', match: 'Unhappy' },
                { word: 'Smart', match: 'Clever' },
                { word: 'Small', match: 'Tiny' },
                { word: 'Angry', match: 'Furious' },
                { word: 'Brave', match: 'Courageous' },
                { word: 'Quiet', match: 'Silent' },
                { word: 'Funny', match: 'Hilarious' },
                { word: 'Beautiful', match: 'Gorgeous' },
                { word: 'Strong', match: 'Powerful' },
                { word: 'Difficult', match: 'Challenging' },
                { word: 'Kind', match: 'Compassionate' },
                { word: 'Tired', match: 'Exhausted' },
                { word: 'Important', match: 'Significant' },
                { word: 'Curious', match: 'Inquisitive' },
                { word: 'Ancient', match: 'Archaic' },
                { word: 'Enormous', match: 'Gigantic' },
                { word: 'Generous', match: 'Charitable' },
            ],
        },
    },

    'Story Fill-In': {
        grade: 'Grade 5',
        type: 'literacy',
        description: 'Drag the correct words from the word bank into the blanks in the story.',
        content: {
            paragraph:
                'One sunny {0}, Maya decided to visit the {1} near her house. She packed a {2} lunch and her favorite {3}. Along the way, she saw a {4} playing in the grass and a {5} flying above the trees. When she arrived, she spread her blanket under a big {6} and began to read her {7}. After eating, she felt {8} and decided to take a short {9} before heading home.',
            blanks: ['morning', 'park', 'delicious', 'book', 'rabbit', 'bird', 'tree', 'story', 'happy', 'nap'],
            wordBank: [
                'morning', 'park', 'delicious', 'book', 'rabbit', 'bird', 'tree', 'story', 'happy', 'nap',
                'evening', 'mall', 'bitter', 'sock', 'elephant', 'airplane', 'stone', 'movie', 'angry', 'race',
            ],
        },
    },

    'Fraction Pizza': {
        grade: 'Grade 5',
        type: 'numeracy',
        description: 'Tap pizza slices to shade the fraction shown.',
        content: {
            rounds: [
                { totalSlices: 2, target: 1, targetLabel: '1/2' },
                { totalSlices: 4, target: 1, targetLabel: '1/4' },
                { totalSlices: 4, target: 2, targetLabel: '2/4' },
                { totalSlices: 4, target: 3, targetLabel: '3/4' },
                { totalSlices: 6, target: 1, targetLabel: '1/6' },
                { totalSlices: 6, target: 2, targetLabel: '2/6' },
                { totalSlices: 6, target: 4, targetLabel: '4/6' },
                { totalSlices: 6, target: 5, targetLabel: '5/6' },
                { totalSlices: 8, target: 1, targetLabel: '1/8' },
                { totalSlices: 8, target: 3, targetLabel: '3/8' },
                { totalSlices: 8, target: 5, targetLabel: '5/8' },
                { totalSlices: 8, target: 6, targetLabel: '6/8' },
                { totalSlices: 10, target: 2, targetLabel: '2/10' },
                { totalSlices: 10, target: 4, targetLabel: '4/10' },
                { totalSlices: 10, target: 7, targetLabel: '7/10' },
                { totalSlices: 10, target: 9, targetLabel: '9/10' },
                { totalSlices: 12, target: 5, targetLabel: '5/12' },
                { totalSlices: 12, target: 7, targetLabel: '7/12' },
                { totalSlices: 12, target: 9, targetLabel: '9/12' },
                { totalSlices: 12, target: 11, targetLabel: '11/12' },
            ],
        },
    },

    'Number Line Runner': {
        grade: 'Grade 5',
        type: 'numeracy',
        description: 'Click the number line to jump the correct number of spaces.',
        content: {
            rounds: [
                { start: 2, steps: 4, operation: '+', answer: 6, min: 0, max: 10 },
                { start: 9, steps: 3, operation: '-', answer: 6, min: 0, max: 10 },
                { start: 5, steps: 5, operation: '+', answer: 10, min: 0, max: 12 },
                { start: 8, steps: 6, operation: '-', answer: 2, min: 0, max: 10 },
                { start: 3, steps: 7, operation: '+', answer: 10, min: 0, max: 14 },
                { start: 12, steps: 4, operation: '-', answer: 8, min: 0, max: 14 },
                { start: 6, steps: 8, operation: '+', answer: 14, min: 0, max: 16 },
                { start: 15, steps: 5, operation: '-', answer: 10, min: 0, max: 16 },
                { start: 4, steps: 9, operation: '+', answer: 13, min: 0, max: 16 },
                { start: 14, steps: 6, operation: '-', answer: 8, min: 0, max: 16 },
                { start: 7, steps: 10, operation: '+', answer: 17, min: 0, max: 20 },
                { start: 18, steps: 7, operation: '-', answer: 11, min: 0, max: 20 },
                { start: 9, steps: 11, operation: '+', answer: 20, min: 0, max: 22 },
                { start: 20, steps: 9, operation: '-', answer: 11, min: 0, max: 22 },
                { start: 5, steps: 12, operation: '+', answer: 17, min: 0, max: 22 },
                { start: 22, steps: 10, operation: '-', answer: 12, min: 0, max: 24 },
                { start: 8, steps: 13, operation: '+', answer: 21, min: 0, max: 24 },
                { start: 24, steps: 11, operation: '-', answer: 13, min: 0, max: 26 },
                { start: 10, steps: 14, operation: '+', answer: 24, min: 0, max: 26 },
                { start: 26, steps: 12, operation: '-', answer: 14, min: 0, max: 28 },
            ],
        },
    },

    // ===== GRADE 6 =====
    'Clue Detective': {
        grade: 'Grade 6',
        type: 'literacy',
        description: 'Click the words that reveal the meaning of the highlighted vocabulary word.',
        content: {
            rounds: [
                {
                    words: ['The', 'artifact', 'was', 'invaluable', '—', 'extremely', 'valuable', 'and', 'impossible', 'to', 'replace', '.'],
                    targetIndex: 3,
                    clueRange: [5, 10],
                },
                {
                    words: ['She', 'was', 'meticulous', ',', 'always', 'checking', 'every', 'detail', 'carefully', 'before', 'submitting', 'her', 'work', '.'],
                    targetIndex: 2,
                    clueRange: [4, 8],
                },
                {
                    words: ['The', 'weather', 'was', 'turbulent', ',', 'with', 'strong', 'winds', 'and', 'heavy', 'rain', 'battering', 'the', 'coast', '.'],
                    targetIndex: 3,
                    clueRange: [5, 10],
                },
                {
                    words: ['The', 'detective', 'was', 'diligent', ',', 'carefully', 'examining', 'every', 'piece', 'of', 'evidence', 'before', 'drawing', 'conclusions', '.'],
                    targetIndex: 3,
                    clueRange: [5, 10],
                },
                {
                    words: ['The', 'old', 'house', 'looked', 'dilapidated', ',', 'with', 'broken', 'windows', 'and', 'a', 'collapsing', 'roof', '.'],
                    targetIndex: 4,
                    clueRange: [6, 12],
                },
                {
                    words: ['Her', 'explanation', 'was', 'ambiguous', ',', 'leaving', 'the', 'class', 'confused', 'about', 'what', 'she', 'truly', 'meant', '.'],
                    targetIndex: 3,
                    clueRange: [5, 13],
                },
                {
                    words: ["The", "magician's", 'trick', 'was', 'baffling', ',', 'and', 'no', 'one', 'in', 'the', 'audience', 'could', 'explain', 'how', 'it', 'worked', '.'],
                    targetIndex: 4,
                    clueRange: [7, 16],
                },
                {
                    words: ['The', 'soup', 'tasted', 'bland', ',', 'lacking', 'any', 'spices', 'or', 'seasoning', 'to', 'give', 'it', 'flavor', '.'],
                    targetIndex: 3,
                    clueRange: [5, 9],
                },
                {
                    words: ["The", "champion's", 'victory', 'was', 'inevitable', ',', 'since', 'no', 'other', 'team', 'could', 'match', 'her', 'skill', 'and', 'speed', '.'],
                    targetIndex: 4,
                    clueRange: [6, 15],
                },
                {
                    words: ['The', 'old', "man's", 'memory', 'was', 'fading', ',', 'and', 'he', 'often', 'forgot', 'where', 'he', 'placed', 'his', 'keys', '.'],
                    targetIndex: 5,
                    clueRange: [7, 15],
                },
                {
                    words: ['The', 'crowd', 'was', 'jubilant', ',', 'cheering', 'loudly', 'and', 'celebrating', 'the', "team's", 'amazing', 'victory', '.'],
                    targetIndex: 3,
                    clueRange: [5, 12],
                },
                {
                    words: ['His', 'argument', 'was', 'persuasive', ',', 'convincing', 'even', 'the', 'most', 'skeptical', 'members', 'of', 'the', 'audience', '.'],
                    targetIndex: 3,
                    clueRange: [5, 13],
                },
                {
                    words: ['The', 'ancient', 'ruins', 'were', 'desolate', ',', 'with', 'no', 'sign', 'of', 'life', 'for', 'miles', 'around', '.'],
                    targetIndex: 4,
                    clueRange: [6, 13],
                },
                {
                    words: ['The', 'new', 'employee', 'was', 'diligent', ',', 'arriving', 'early', 'and', 'staying', 'late', 'to', 'finish', 'every', 'task', '.'],
                    targetIndex: 4,
                    clueRange: [6, 14],
                },
                {
                    words: ["The", "scientist's", 'discovery', 'was', 'groundbreaking', ',', 'changing', 'how', 'people', 'understood', 'the', 'universe', 'forever', '.'],
                    targetIndex: 4,
                    clueRange: [6, 12],
                },
                {
                    words: ["The", "politician's", 'speech', 'was', 'eloquent', ',', 'filled', 'with', 'powerful', 'words', 'that', 'moved', 'the', 'entire', 'crowd', '.'],
                    targetIndex: 4,
                    clueRange: [6, 14],
                },
                {
                    words: ['The', 'abandoned', 'building', 'was', 'derelict', ',', 'its', 'walls', 'crumbling', 'and', 'windows', 'shattered', 'by', 'years', 'of', 'neglect', '.'],
                    targetIndex: 4,
                    clueRange: [6, 15],
                },
                {
                    words: ["The", "professor's", 'lecture', 'was', 'tedious', ',', 'dragging', 'on', 'for', 'hours', 'without', 'a', 'single', 'interesting', 'point', '.'],
                    targetIndex: 4,
                    clueRange: [6, 14],
                },
                {
                    words: ["The", "athlete's", 'performance', 'was', 'exceptional', ',', 'breaking', 'three', 'records', 'in', 'a', 'single', 'afternoon', '.'],
                    targetIndex: 4,
                    clueRange: [6, 12],
                },
                {
                    words: ["The", "company's", 'decision', 'was', 'controversial', ',', 'sparking', 'heated', 'debate', 'among', 'employees', 'and', 'shareholders', 'alike', '.'],
                    targetIndex: 4,
                    clueRange: [6, 13],
                },
            ],
        },
    },

    'Word Web Builder': {
        grade: 'Grade 6',
        type: 'literacy',
        description: 'Drag the words that relate to the central concept into the web.',
        content: {
            centralWord: 'OCEAN',
            correctWords: ['Wave', 'Coral', 'Tide', 'Current', 'Reef', 'Shark', 'Plankton', 'Shore', 'Saltwater', 'Whale'],
            distractorWords: ['Mountain', 'Desert', 'Cactus', 'Volcano', 'Forest', 'Glacier', 'Meadow', 'Canyon', 'Prairie', 'Tundra'],
        },
    },

    'Balance Scale': {
        grade: 'Grade 6',
        type: 'numeracy',
        description: 'Drag weights onto the right side until the scale balances.',
        content: {
            rounds: [
                { leftValue: 9, weights: [4, 5, 2, 6, 3] },
                { leftValue: 10, weights: [3, 7, 2, 5, 4] },
                { leftValue: 11, weights: [4, 7, 2, 6, 3] },
                { leftValue: 12, weights: [5, 7, 4, 3, 6] },
                { leftValue: 13, weights: [6, 7, 3, 5, 4] },
                { leftValue: 14, weights: [6, 8, 3, 5, 4] },
                { leftValue: 15, weights: [8, 7, 3, 5, 2] },
                { leftValue: 16, weights: [9, 7, 4, 6, 3] },
                { leftValue: 17, weights: [9, 8, 4, 6, 3] },
                { leftValue: 18, weights: [10, 8, 4, 6, 3] },
                { leftValue: 19, weights: [11, 8, 5, 7, 3] },
                { leftValue: 20, weights: [12, 8, 5, 7, 3] },
                { leftValue: 21, weights: [13, 8, 5, 7, 3] },
                { leftValue: 22, weights: [14, 8, 5, 7, 3] },
                { leftValue: 23, weights: [15, 8, 5, 7, 3] },
                { leftValue: 24, weights: [16, 8, 5, 7, 3] },
                { leftValue: 25, weights: [17, 8, 5, 7, 3] },
                { leftValue: 26, weights: [18, 8, 5, 7, 3] },
                { leftValue: 28, weights: [20, 8, 5, 7, 3] },
                { leftValue: 30, weights: [22, 8, 5, 7, 3] },
            ],
        },
    },

    'Graph Builder': {
        grade: 'Grade 6',
        type: 'numeracy',
        description: 'Click each bar to build it up to match the data, then answer a quick question about your graph.',
        content: {
            rounds: [
                {
                    title: 'Favorite Fruits Survey',
                    maxValue: 10,
                    categories: [{ label: 'Apple', target: 4 }, { label: 'Banana', target: 7 }, { label: 'Grape', target: 3 }],
                    question: 'Which fruit got the most votes?',
                    answer: 'Banana',
                },
                {
                    title: 'Pets Owned by Classmates',
                    maxValue: 8,
                    categories: [{ label: 'Dog', target: 6 }, { label: 'Cat', target: 5 }, { label: 'Fish', target: 2 }],
                    question: 'Which pet is the least common?',
                    answer: 'Fish',
                },
                {
                    title: 'Favorite Sports',
                    maxValue: 12,
                    categories: [{ label: 'Basketball', target: 8 }, { label: 'Soccer', target: 10 }, { label: 'Tennis', target: 4 }],
                    question: 'Which sport is most popular?',
                    answer: 'Soccer',
                },
                {
                    title: 'Ice Cream Flavors',
                    maxValue: 10,
                    categories: [{ label: 'Vanilla', target: 5 }, { label: 'Chocolate', target: 9 }, { label: 'Strawberry', target: 3 }],
                    question: 'Which flavor is most popular?',
                    answer: 'Chocolate',
                },
                {
                    title: 'Weekly Rainfall (mm)',
                    maxValue: 10,
                    categories: [{ label: 'Mon', target: 3 }, { label: 'Tue', target: 7 }, { label: 'Wed', target: 5 }],
                    question: 'Which day had the most rain?',
                    answer: 'Tue',
                },
                {
                    title: 'Books Read This Month',
                    maxValue: 8,
                    categories: [{ label: 'Fiction', target: 6 }, { label: 'Non-Fiction', target: 4 }, { label: 'Comics', target: 7 }],
                    question: 'Which category had the most books?',
                    answer: 'Comics',
                },
                {
                    title: 'Favorite Subjects',
                    maxValue: 10,
                    categories: [{ label: 'Math', target: 7 }, { label: 'Science', target: 9 }, { label: 'Art', target: 5 }],
                    question: 'Which subject is most popular?',
                    answer: 'Science',
                },
                {
                    title: 'Classroom Pets Wanted',
                    maxValue: 8,
                    categories: [{ label: 'Hamster', target: 3 }, { label: 'Turtle', target: 6 }, { label: 'Bird', target: 4 }],
                    question: 'Which pet is most wanted?',
                    answer: 'Turtle',
                },
                {
                    title: 'Vehicles in the Parking Lot',
                    maxValue: 12,
                    categories: [{ label: 'Cars', target: 10 }, { label: 'Trucks', target: 6 }, { label: 'Motorcycles', target: 3 }],
                    question: 'Which vehicle type is most common?',
                    answer: 'Cars',
                },
                {
                    title: 'Favorite Colors',
                    maxValue: 10,
                    categories: [{ label: 'Blue', target: 8 }, { label: 'Red', target: 5 }, { label: 'Green', target: 6 }],
                    question: 'Which color is most popular?',
                    answer: 'Blue',
                },
                {
                    title: 'Snacks Sold',
                    maxValue: 12,
                    categories: [{ label: 'Chips', target: 9 }, { label: 'Cookies', target: 11 }, { label: 'Fruit', target: 6 }],
                    question: 'Which snack sold the most?',
                    answer: 'Cookies',
                },
                {
                    title: 'Hours Spent on Homework',
                    maxValue: 8,
                    categories: [{ label: 'Mon', target: 5 }, { label: 'Wed', target: 7 }, { label: 'Fri', target: 3 }],
                    question: 'Which day had the most homework?',
                    answer: 'Wed',
                },
                {
                    title: 'Favorite Music Genres',
                    maxValue: 10,
                    categories: [{ label: 'Pop', target: 9 }, { label: 'Rock', target: 6 }, { label: 'Jazz', target: 4 }],
                    question: 'Which genre is most popular?',
                    answer: 'Pop',
                },
                {
                    title: 'Recycling Collected (kg)',
                    maxValue: 12,
                    categories: [{ label: 'Paper', target: 10 }, { label: 'Plastic', target: 7 }, { label: 'Glass', target: 5 }],
                    question: 'Which material had the most collected?',
                    answer: 'Paper',
                },
                {
                    title: 'Favorite Board Games',
                    maxValue: 10,
                    categories: [{ label: 'Chess', target: 6 }, { label: 'Monopoly', target: 8 }, { label: 'Checkers', target: 4 }],
                    question: 'Which game is most popular?',
                    answer: 'Monopoly',
                },
                {
                    title: 'Students per Club',
                    maxValue: 12,
                    categories: [{ label: 'Art Club', target: 7 }, { label: 'Science Club', target: 11 }, { label: 'Music Club', target: 5 }],
                    question: 'Which club has the most students?',
                    answer: 'Science Club',
                },
                {
                    title: 'Daily Steps (thousands)',
                    maxValue: 10,
                    categories: [{ label: 'Mon', target: 6 }, { label: 'Tue', target: 9 }, { label: 'Wed', target: 4 }],
                    question: 'Which day had the most steps?',
                    answer: 'Tue',
                },
                {
                    title: 'Favorite Season',
                    maxValue: 10,
                    categories: [{ label: 'Summer', target: 8 }, { label: 'Winter', target: 5 }, { label: 'Spring', target: 7 }],
                    question: 'Which season is most popular?',
                    answer: 'Summer',
                },
                {
                    title: 'Fundraiser Earnings ($100s)',
                    maxValue: 12,
                    categories: [{ label: 'Grade A', target: 9 }, { label: 'Grade B', target: 12 }, { label: 'Grade C', target: 6 }],
                    question: 'Which grade raised the most?',
                    answer: 'Grade B',
                },
                {
                    title: 'Video Game Genres',
                    maxValue: 10,
                    categories: [{ label: 'Action', target: 9 }, { label: 'Puzzle', target: 5 }, { label: 'Adventure', target: 7 }],
                    question: 'Which genre is most popular?',
                    answer: 'Action',
                },
            ],
        },
    },
};

export default gameDefinitions;
