// Static content for every interactive game.
// KEYS MUST MATCH the game_title strings used in
// app/Http/Controllers/Teacher/GameController.php EXACTLY.
//
// All 24 games: 4 per grade × 3 grades, 2 types each

const gameDefinitions = {
    // ===== GRADE 4 =====
    'Word Builder': {
        grade: 'Grade 4',
        type: 'literacy',
        description: 'Drag the letters into the blanks to spell the word shown by the picture.',
        content: {
            rounds: [
                { image: '🐱', word: 'CAT', letters: ['C', 'A', 'T', 'X', 'B'] },
                { image: '🐶', word: 'DOG', letters: ['D', 'O', 'G', 'P', 'N'] },
                { image: '🌞', word: 'SUN', letters: ['S', 'U', 'N', 'M', 'Y'] },
                { image: '🐷', word: 'PIG', letters: ['P', 'I', 'G', 'D', 'T'] },
                { image: '🐝', word: 'BEE', letters: ['B', 'E', 'E', 'R', 'L'] },
                { image: '🐟', word: 'FISH', letters: ['F', 'I', 'S', 'H', 'K', 'W'] },
                { image: '🐸', word: 'FROG', letters: ['F', 'R', 'O', 'G', 'S', 'L'] },
                { image: '🦆', word: 'DUCK', letters: ['D', 'U', 'C', 'K', 'B', 'T'] },
                { image: '🐻', word: 'BEAR', letters: ['B', 'E', 'A', 'R', 'S', 'N'] },
                { image: '🦁', word: 'LION', letters: ['L', 'I', 'O', 'N', 'T', 'M'] },
                { image: '🐐', word: 'GOAT', letters: ['G', 'O', 'A', 'T', 'S', 'B'] },
                { image: '🦀', word: 'CRAB', letters: ['C', 'R', 'A', 'B', 'T', 'N'] },
                { image: '🐴', word: 'HORSE', letters: ['H', 'O', 'R', 'S', 'E', 'T', 'P'] },
                { image: '🍎', word: 'APPLE', letters: ['A', 'P', 'P', 'L', 'E', 'S', 'T'] },
                { image: '🍇', word: 'GRAPE', letters: ['G', 'R', 'A', 'P', 'E', 'T', 'N'] },
                { image: '🐯', word: 'TIGER', letters: ['T', 'I', 'G', 'E', 'R', 'S', 'B'] },
                { image: '🦓', word: 'ZEBRA', letters: ['Z', 'E', 'B', 'R', 'A', 'T', 'N'] },
                { image: '🐋', word: 'WHALE', letters: ['W', 'H', 'A', 'L', 'E', 'T', 'S'] },
                { image: '🐒', word: 'MONKEY', letters: ['M', 'O', 'N', 'K', 'E', 'Y', 'T', 'S'] },
                { image: '🐬', word: 'DOLPHIN', letters: ['D', 'O', 'L', 'P', 'H', 'I', 'N', 'T', 'S'] },
            ],
        },
    },

    'Sentence Scramble': {
        grade: 'Grade 4',
        type: 'literacy',
        description: 'Drag the words into the correct order to form a proper sentence.',
        content: {
            rounds: [
                { correct: ['The', 'cat', 'is', 'sleeping'], scrambled: ['sleeping', 'The', 'cat', 'is'] },
                { correct: ['We', 'play', 'in', 'the', 'park'], scrambled: ['park', 'We', 'the', 'in', 'play'] },
                { correct: ['I', 'like', 'to', 'read', 'books'], scrambled: ['read', 'I', 'books', 'to', 'like'] },
                { correct: ['She', 'sings', 'a', 'happy', 'song'], scrambled: ['a', 'song', 'She', 'happy', 'sings'] },
                { correct: ['The', 'sun', 'is', 'very', 'bright'], scrambled: ['very', 'The', 'bright', 'sun', 'is'] },
                { correct: ['My', 'dog', 'loves', 'to', 'run'], scrambled: ['to', 'My', 'run', 'dog', 'loves'] },
                { correct: ['He', 'eats', 'breakfast', 'every', 'morning'], scrambled: ['every', 'He', 'morning', 'eats', 'breakfast'] },
                { correct: ['They', 'walk', 'to', 'school', 'together'], scrambled: ['school', 'They', 'together', 'walk', 'to'] },
                { correct: ['We', 'watch', 'movies', 'on', 'weekends'], scrambled: ['on', 'We', 'weekends', 'watch', 'movies'] },
                { correct: ['The', 'bird', 'flies', 'over', 'the', 'tree'], scrambled: ['over', 'The', 'tree', 'bird', 'the', 'flies'] },
                { correct: ['The', 'children', 'play', 'in', 'the', 'garden'], scrambled: ['in', 'The', 'garden', 'children', 'the', 'play'] },
                { correct: ['She', 'reads', 'a', 'book', 'before', 'bed'], scrambled: ['before', 'She', 'bed', 'reads', 'a', 'book'] },
                { correct: ['My', 'family', 'enjoys', 'eating', 'dinner', 'together'], scrambled: ['dinner', 'My', 'together', 'family', 'enjoys', 'eating'] },
                { correct: ['The', 'teacher', 'explains', 'the', 'lesson', 'clearly'], scrambled: ['clearly', 'The', 'lesson', 'teacher', 'explains', 'the'] },
                { correct: ['He', 'rides', 'his', 'bicycle', 'to', 'the', 'park'], scrambled: ['to', 'He', 'park', 'rides', 'the', 'his', 'bicycle'] },
                { correct: ['The', 'rain', 'fell', 'softly', 'on', 'the', 'roof'], scrambled: ['on', 'The', 'roof', 'fell', 'the', 'rain', 'softly'] },
                { correct: ['We', 'planted', 'flowers', 'in', 'our', 'garden', 'yesterday'], scrambled: ['yesterday', 'We', 'garden', 'planted', 'our', 'in', 'flowers'] },
                { correct: ['The', 'students', 'listened', 'carefully', 'to', 'the', 'story'], scrambled: ['to', 'The', 'story', 'listened', 'the', 'students', 'carefully'] },
                { correct: ['My', 'best', 'friend', 'and', 'I', 'love', 'drawing'], scrambled: ['love', 'My', 'drawing', 'best', 'I', 'friend', 'and'] },
                { correct: ['The', 'farmer', 'feeds', 'the', 'animals', 'every', 'morning'], scrambled: ['every', 'The', 'morning', 'feeds', 'the', 'farmer', 'animals'] },
            ],
        },
    },

    'Rhyme Match': {
        grade: 'Grade 4',
        type: 'literacy',
        description: 'Click the word that rhymes with the target word.',
        content: {
            rounds: [
                { target: 'CAT', options: [{ word: 'BAT', isRhyme: true }, { word: 'DOG', isRhyme: false }, { word: 'HAT', isRhyme: true }, { word: 'SUN', isRhyme: false }] },
                { target: 'DOG', options: [{ word: 'LOG', isRhyme: true }, { word: 'CAT', isRhyme: false }, { word: 'FOG', isRhyme: true }, { word: 'BAT', isRhyme: false }] },
                { target: 'SUN', options: [{ word: 'FUN', isRhyme: true }, { word: 'CAT', isRhyme: false }, { word: 'RUN', isRhyme: true }, { word: 'DOG', isRhyme: false }] },
                { target: 'FISH', options: [{ word: 'WISH', isRhyme: true }, { word: 'BAT', isRhyme: false }, { word: 'DISH', isRhyme: true }, { word: 'CAT', isRhyme: false }] },
                { target: 'TREE', options: [{ word: 'BEE', isRhyme: true }, { word: 'DOG', isRhyme: false }, { word: 'SEE', isRhyme: true }, { word: 'RUN', isRhyme: false }] },
                { target: 'RING', options: [{ word: 'SING', isRhyme: true }, { word: 'BAT', isRhyme: false }, { word: 'WING', isRhyme: true }, { word: 'CAT', isRhyme: false }] },
                { target: 'BOOK', options: [{ word: 'LOOK', isRhyme: true }, { word: 'RUN', isRhyme: false }, { word: 'COOK', isRhyme: true }, { word: 'SUN', isRhyme: false }] },
                { target: 'STAR', options: [{ word: 'CAR', isRhyme: true }, { word: 'BAT', isRhyme: false }, { word: 'JAR', isRhyme: true }, { word: 'DOG', isRhyme: false }] },
                { target: 'BEAR', options: [{ word: 'CARE', isRhyme: true }, { word: 'RUN', isRhyme: false }, { word: 'HAIR', isRhyme: true }, { word: 'CAT', isRhyme: false }] },
                { target: 'NIGHT', options: [{ word: 'LIGHT', isRhyme: true }, { word: 'DAY', isRhyme: false }, { word: 'FIGHT', isRhyme: true }, { word: 'SUN', isRhyme: false }] },
                { target: 'RAIN', options: [{ word: 'PAIN', isRhyme: true }, { word: 'SUN', isRhyme: false }, { word: 'GAIN', isRhyme: true }, { word: 'DAY', isRhyme: false }] },
                { target: 'BELL', options: [{ word: 'TELL', isRhyme: true }, { word: 'RUN', isRhyme: false }, { word: 'WELL', isRhyme: true }, { word: 'CAT', isRhyme: false }] },
                { target: 'MOON', options: [{ word: 'SOON', isRhyme: true }, { word: 'DAY', isRhyme: false }, { word: 'NOON', isRhyme: true }, { word: 'SUN', isRhyme: false }] },
                { target: 'CLOCK', options: [{ word: 'ROCK', isRhyme: true }, { word: 'DAY', isRhyme: false }, { word: 'LOCK', isRhyme: true }, { word: 'RUN', isRhyme: false }] },
                { target: 'KING', options: [{ word: 'RING', isRhyme: true }, { word: 'RUN', isRhyme: false }, { word: 'THING', isRhyme: true }, { word: 'CAT', isRhyme: false }] },
                { target: 'BEE', options: [{ word: 'TEE', isRhyme: true }, { word: 'CAT', isRhyme: false }, { word: 'FREE', isRhyme: true }, { word: 'DOG', isRhyme: false }] },
                { target: 'BOX', options: [{ word: 'FOX', isRhyme: true }, { word: 'RUN', isRhyme: false }, { word: 'LOCKS', isRhyme: true }, { word: 'SUN', isRhyme: false }] },
                { target: 'KITE', options: [{ word: 'BITE', isRhyme: true }, { word: 'DAY', isRhyme: false }, { word: 'SITE', isRhyme: true }, { word: 'RUN', isRhyme: false }] },
                { target: 'PEN', options: [{ word: 'TEN', isRhyme: true }, { word: 'CAT', isRhyme: false }, { word: 'HEN', isRhyme: true }, { word: 'DOG', isRhyme: false }] },
                { target: 'HAT', options: [{ word: 'RAT', isRhyme: true }, { word: 'SUN', isRhyme: false }, { word: 'SAT', isRhyme: true }, { word: 'DOG', isRhyme: false }] },
            ],
        },
    },

    'Letter Hunt': {
        grade: 'Grade 4',
        type: 'literacy',
        description: 'Click the letters in the correct order to spell the word shown.',
        content: {
            rounds: [
                { word: 'CAT', cells: ['C', 'A', 'T', 'X', 'B', 'D', 'F', 'G'], path: [0, 1, 2] },
                { word: 'DOG', cells: ['D', 'O', 'G', 'P', 'N', 'R', 'S', 'T'], path: [0, 1, 2] },
                { word: 'FISH', cells: ['F', 'I', 'S', 'H', 'K', 'W', 'L', 'M'], path: [0, 1, 2, 3] },
                { word: 'BEE', cells: ['B', 'E', 'E', 'R', 'L', 'M', 'N', 'P'], path: [0, 1, 2] },
                { word: 'SUN', cells: ['S', 'U', 'N', 'M', 'Y', 'Z', 'A', 'C'], path: [0, 1, 2] },
                { word: 'FROG', cells: ['F', 'R', 'O', 'G', 'S', 'L', 'T', 'V'], path: [0, 1, 2, 3] },
                { word: 'DUCK', cells: ['D', 'U', 'C', 'K', 'B', 'T', 'M', 'N'], path: [0, 1, 2, 3] },
                { word: 'BEAR', cells: ['B', 'E', 'A', 'R', 'S', 'N', 'P', 'Q'], path: [0, 1, 2, 3] },
                { word: 'LION', cells: ['L', 'I', 'O', 'N', 'T', 'M', 'X', 'Y'], path: [0, 1, 2, 3] },
                { word: 'GOAT', cells: ['G', 'O', 'A', 'T', 'S', 'B', 'K', 'L'], path: [0, 1, 2, 3] },
                { word: 'CRAB', cells: ['C', 'R', 'A', 'B', 'T', 'N', 'M', 'P'], path: [0, 1, 2, 3] },
                { word: 'HORSE', cells: ['H', 'O', 'R', 'S', 'E', 'T', 'P', 'Q'], path: [0, 1, 2, 3, 4] },
                { word: 'APPLE', cells: ['A', 'P', 'P', 'L', 'E', 'S', 'T', 'V'], path: [0, 1, 2, 3, 4] },
                { word: 'GRAPE', cells: ['G', 'R', 'A', 'P', 'E', 'T', 'N', 'M'], path: [0, 1, 2, 3, 4] },
                { word: 'TIGER', cells: ['T', 'I', 'G', 'E', 'R', 'S', 'B', 'K'], path: [0, 1, 2, 3, 4] },
                { word: 'ZEBRA', cells: ['Z', 'E', 'B', 'R', 'A', 'T', 'N', 'P'], path: [0, 1, 2, 3, 4] },
                { word: 'WHALE', cells: ['W', 'H', 'A', 'L', 'E', 'T', 'S', 'K'], path: [0, 1, 2, 3, 4] },
                { word: 'MONKEY', cells: ['M', 'O', 'N', 'K', 'E', 'Y', 'T', 'S'], path: [0, 1, 2, 3, 4, 5] },
                { word: 'DOLPHIN', cells: ['D', 'O', 'L', 'P', 'H', 'I', 'N', 'T'], path: [0, 1, 2, 3, 4, 5, 6] },
                { word: 'ELEPHANT', cells: ['E', 'L', 'E', 'P', 'H', 'A', 'N', 'T'], path: [0, 1, 2, 3, 4, 5, 6, 7] },
            ],
        },
    },

    'Balloon Pop Math': {
        grade: 'Grade 4',
        type: 'numeracy',
        description: 'Tap only the balloons that equal the target number before time runs out.',
        content: {
            rounds: [
                { target: 5, numbers: [5, 3, 5, 7, 2, 5, 8, 4] },
                { target: 8, numbers: [8, 3, 8, 5, 6, 8, 2, 7] },
                { target: 6, numbers: [6, 9, 3, 6, 7, 6, 1, 8] },
                { target: 10, numbers: [10, 4, 10, 7, 3, 10, 6, 9] },
                { target: 7, numbers: [7, 2, 7, 9, 4, 7, 3, 8] },
                { target: 9, numbers: [9, 4, 9, 6, 2, 9, 7, 5] },
                { target: 12, numbers: [5, 12, 9, 12, 4, 10, 12, 6] },
                { target: 11, numbers: [11, 3, 11, 7, 5, 11, 9, 2] },
                { target: 13, numbers: [13, 5, 13, 8, 4, 13, 10, 6] },
                { target: 14, numbers: [14, 6, 14, 9, 3, 14, 11, 7] },
                { target: 15, numbers: [15, 8, 15, 10, 6, 15, 12, 9] },
                { target: 16, numbers: [16, 7, 16, 10, 5, 16, 12, 9] },
                { target: 17, numbers: [17, 8, 17, 11, 6, 17, 13, 9] },
                { target: 18, numbers: [18, 9, 18, 12, 6, 18, 14, 10] },
                { target: 19, numbers: [19, 9, 19, 13, 7, 19, 15, 10] },
                { target: 20, numbers: [20, 10, 20, 15, 8, 20, 17, 12] },
                { target: 21, numbers: [21, 10, 21, 14, 7, 21, 17, 11] },
                { target: 22, numbers: [22, 11, 22, 15, 8, 22, 17, 12] },
                { target: 24, numbers: [24, 12, 24, 16, 8, 24, 19, 13] },
                { target: 25, numbers: [25, 13, 25, 18, 9, 25, 20, 15] },
            ],
        },
    },

    'Sorting Baskets': {
        grade: 'Grade 4',
        type: 'numeracy',
        description: 'Drag each number into the correct basket: Even or Odd.',
        content: {
            rounds: [
                {
                    basketA: 'Even',
                    basketB: 'Odd',
                    items: [
                        { value: 4, type: 'Even' },
                        { value: 7, type: 'Odd' },
                        { value: 10, type: 'Even' },
                        { value: 3, type: 'Odd' },
                        { value: 8, type: 'Even' },
                        { value: 5, type: 'Odd' },
                        { value: 12, type: 'Even' },
                        { value: 9, type: 'Odd' },
                        { value: 15, type: 'Odd' },
                        { value: 18, type: 'Even' },
                        { value: 21, type: 'Odd' },
                        { value: 24, type: 'Even' },
                        { value: 27, type: 'Odd' },
                        { value: 30, type: 'Even' },
                        { value: 33, type: 'Odd' },
                        { value: 36, type: 'Even' },
                        { value: 39, type: 'Odd' },
                        { value: 42, type: 'Even' },
                        { value: 45, type: 'Odd' },
                        { value: 50, type: 'Even' },
                    ],
                },
            ],
        },
    },

    'Coin Counter': {
        grade: 'Grade 4',
        type: 'numeracy',
        description: 'Drag coins into the jar until the total equals the target amount.',
        content: {
            rounds: [
                { target: 15, coins: [5, 10, 3, 7, 8] },
                { target: 20, coins: [10, 5, 8, 7, 3] },
                { target: 25, coins: [15, 10, 5, 3, 7] },
                { target: 12, coins: [5, 7, 3, 4, 8] },
                { target: 18, coins: [10, 5, 3, 8, 2] },
                { target: 22, coins: [10, 7, 5, 3, 8] },
                { target: 30, coins: [15, 10, 5, 3, 7] },
                { target: 28, coins: [15, 10, 3, 8, 2] },
                { target: 35, coins: [20, 10, 5, 3, 7] },
                { target: 40, coins: [20, 15, 5, 3, 2] },
                { target: 17, coins: [10, 5, 7, 3, 2] },
                { target: 24, coins: [15, 5, 4, 3, 7] },
                { target: 21, coins: [10, 8, 5, 3, 2] },
                { target: 32, coins: [20, 7, 5, 3, 2] },
                { target: 19, coins: [10, 7, 5, 2, 3] },
                { target: 27, coins: [15, 10, 5, 2, 7] },
                { target: 36, coins: [20, 10, 5, 3, 1] },
                { target: 23, coins: [15, 5, 3, 2, 8] },
                { target: 26, coins: [15, 7, 4, 3, 2] },
                { target: 33, coins: [20, 10, 3, 2, 5] },
            ],
        },
    },

    'Skip Counting Path': {
        grade: 'Grade 4',
        type: 'numeracy',
        description: 'Click the stepping stones in order to skip-count along the path.',
        content: {
            rounds: [
                { startAt: 2, skipBy: 2, cells: [2, 3, 4, 5, 6, 7, 8], path: [0, 2, 4, 6] },
                { startAt: 10, skipBy: 2, cells: [10, 11, 12, 13, 14, 15, 16], path: [0, 2, 4, 6] },
                { startAt: 5, skipBy: 5, cells: [5, 7, 10, 12, 15, 17, 20], path: [0, 2, 4, 6] },
                { startAt: 20, skipBy: 5, cells: [20, 22, 25, 27, 30, 32, 35], path: [0, 2, 4, 6] },
                { startAt: 10, skipBy: 10, cells: [10, 15, 20, 25, 30, 35, 40], path: [0, 2, 4, 6] },
                { startAt: 50, skipBy: 10, cells: [50, 55, 60, 65, 70, 75, 80], path: [0, 2, 4, 6] },
                { startAt: 3, skipBy: 3, cells: [3, 4, 6, 7, 9, 10, 12], path: [0, 2, 4, 6] },
                { startAt: 15, skipBy: 3, cells: [15, 16, 18, 19, 21, 22, 24], path: [0, 2, 4, 6] },
                { startAt: 4, skipBy: 4, cells: [4, 5, 8, 9, 12, 13, 16], path: [0, 2, 4, 6] },
                { startAt: 20, skipBy: 4, cells: [20, 21, 24, 25, 28, 29, 32], path: [0, 2, 4, 6] },
                { startAt: 20, skipBy: 2, cells: [20, 21, 22, 23, 24, 25, 26, 27, 28], path: [0, 2, 4, 6, 8] },
                { startAt: 35, skipBy: 5, cells: [35, 37, 40, 42, 45, 47, 50, 52, 55], path: [0, 2, 4, 6, 8] },
                { startAt: 100, skipBy: 10, cells: [100, 105, 110, 115, 120, 125, 130, 135, 140], path: [0, 2, 4, 6, 8] },
                { startAt: 30, skipBy: 3, cells: [30, 31, 33, 34, 36, 37, 39, 40, 42], path: [0, 2, 4, 6, 8] },
                { startAt: 40, skipBy: 4, cells: [40, 41, 44, 45, 48, 49, 52, 53, 56], path: [0, 2, 4, 6, 8] },
                { startAt: 50, skipBy: 2, cells: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60], path: [0, 2, 4, 6, 8, 10] },
                { startAt: 60, skipBy: 5, cells: [60, 62, 65, 67, 70, 72, 75, 77, 80, 82, 85], path: [0, 2, 4, 6, 8, 10] },
                { startAt: 150, skipBy: 10, cells: [150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200], path: [0, 2, 4, 6, 8, 10] },
                { startAt: 60, skipBy: 3, cells: [60, 61, 63, 64, 66, 67, 69, 70, 72, 73, 75], path: [0, 2, 4, 6, 8, 10] },
                { startAt: 80, skipBy: 4, cells: [80, 81, 84, 85, 88, 89, 92, 93, 96, 97, 100], path: [0, 2, 4, 6, 8, 10] },
            ],
        },
    },

    // ===== GRADE 5 =====
    'Match the Meaning': {
        grade: 'Grade 5',
        type: 'literacy',
        description: 'Drag each word on the left to its matching synonym on the right.',
        content: {
            pairs: [
                { word: 'Happy', match: 'Joyful' },
                { word: 'Big', match: 'Large' },
                { word: 'Fast', match: 'Quick' },
                { word: 'Sad', match: 'Unhappy' },
                { word: 'Smart', match: 'Clever' },
                { word: 'Small', match: 'Tiny' },
                { word: 'Angry', match: 'Furious' },
                { word: 'Brave', match: 'Courageous' },
                { word: 'Quiet', match: 'Silent' },
                { word: 'Funny', match: 'Hilarious' },
                { word: 'Beautiful', match: 'Gorgeous' },
                { word: 'Strong', match: 'Powerful' },
                { word: 'Difficult', match: 'Challenging' },
                { word: 'Kind', match: 'Compassionate' },
                { word: 'Tired', match: 'Exhausted' },
                { word: 'Important', match: 'Significant' },
                { word: 'Curious', match: 'Inquisitive' },
                { word: 'Ancient', match: 'Archaic' },
                { word: 'Enormous', match: 'Gigantic' },
                { word: 'Generous', match: 'Charitable' },
            ],
        },
    },

    'Story Fill-In': {
        grade: 'Grade 5',
        type: 'literacy',
        description: 'Drag the correct words from the word bank into the blanks in the story.',
        content: {
            paragraph:
                'One sunny {0}, Maya decided to visit the {1} near her house. She packed a {2} lunch and her favorite {3}. Along the way, she saw a {4} playing in the grass and a {5} flying above the trees. When she arrived, she spread her blanket under a big {6} and began to read her {7}. After eating, she felt {8} and decided to take a short {9} before heading home.',
            blanks: ['morning', 'park', 'delicious', 'book', 'rabbit', 'bird', 'tree', 'story', 'happy', 'nap'],
            wordBank: [
                'morning', 'park', 'delicious', 'book', 'rabbit', 'bird', 'tree', 'story', 'happy', 'nap',
                'evening', 'mall', 'bitter', 'sock', 'elephant', 'airplane', 'stone', 'movie', 'angry', 'race',
            ],
        },
    },

    'Compound Word Combiner': {
        grade: 'Grade 5',
        type: 'literacy',
        description: 'Drag each word on the left onto its matching half to build a compound word.',
        content: {
            pairs: [
                { word: 'Sun', match: 'flower' },
                { word: 'Foot', match: 'ball' },
                { word: 'Rain', match: 'bow' },
                { word: 'Butter', match: 'fly' },
                { word: 'Snow', match: 'man' },
                { word: 'Tooth', match: 'brush' },
                { word: 'Basket', match: 'ball' },
                { word: 'Note', match: 'book' },
                { word: 'Grand', match: 'father' },
                { word: 'Fire', match: 'fighter' },
                { word: 'Star', match: 'fish' },
                { word: 'Air', match: 'plane' },
                { word: 'Back', match: 'pack' },
                { word: 'Play', match: 'ground' },
                { word: 'Sand', match: 'castle' },
                { word: 'Water', match: 'fall' },
                { word: 'Home', match: 'work' },
                { word: 'Moon', match: 'light' },
                { word: 'Class', match: 'room' },
                { word: 'Bed', match: 'room' },
            ],
        },
    },

    'Analogy Solver': {
        grade: 'Grade 5',
        type: 'literacy',
        description: 'Click the word that completes the analogy.',
        content: {
            rounds: [
                { prompt: 'Hot is to Cold as Up is to ___', options: ['Down', 'Left', 'Sun', 'Fast'], correct: 'Down' },
                { prompt: 'Big is to Small as Fast is to ___', options: ['Slow', 'Loud', 'Round', 'Blue'], correct: 'Slow' },
                { prompt: 'Happy is to Sad as Day is to ___', options: ['Night', 'Bright', 'Warm', 'Long'], correct: 'Night' },
                { prompt: 'Bird is to Fly as Fish is to ___', options: ['Swim', 'Walk', 'Sing', 'Crawl'], correct: 'Swim' },
                { prompt: 'Dog is to Puppy as Cat is to ___', options: ['Kitten', 'Cub', 'Calf', 'Chick'], correct: 'Kitten' },
                { prompt: 'Author is to Book as Painter is to ___', options: ['Painting', 'Brush', 'Museum', 'Color'], correct: 'Painting' },
                { prompt: 'Doctor is to Hospital as Teacher is to ___', options: ['School', 'Book', 'Class', 'Desk'], correct: 'School' },
                { prompt: 'Finger is to Hand as Toe is to ___', options: ['Foot', 'Leg', 'Shoe', 'Ankle'], correct: 'Foot' },
                { prompt: 'Leaf is to Tree as Petal is to ___', options: ['Flower', 'Root', 'Seed', 'Stem'], correct: 'Flower' },
                { prompt: 'King is to Crown as Knight is to ___', options: ['Armor', 'Castle', 'Horse', 'Sword'], correct: 'Armor' },
                { prompt: 'Winter is to Cold as Summer is to ___', options: ['Hot', 'Rainy', 'Windy', 'Dark'], correct: 'Hot' },
                { prompt: 'Pen is to Write as Scissors is to ___', options: ['Cut', 'Draw', 'Fold', 'Glue'], correct: 'Cut' },
                { prompt: 'Baker is to Bread as Chef is to ___', options: ['Meal', 'Oven', 'Kitchen', 'Plate'], correct: 'Meal' },
                { prompt: 'Ocean is to Wave as Desert is to ___', options: ['Sand', 'Cactus', 'Heat', 'Camel'], correct: 'Sand' },
                { prompt: 'Caterpillar is to Butterfly as Tadpole is to ___', options: ['Frog', 'Fish', 'Snake', 'Turtle'], correct: 'Frog' },
                { prompt: 'Novel is to Chapter as Song is to ___', options: ['Verse', 'Note', 'Melody', 'Beat'], correct: 'Verse' },
                { prompt: 'Thermometer is to Temperature as Ruler is to ___', options: ['Length', 'Weight', 'Time', 'Sound'], correct: 'Length' },
                { prompt: 'Whisper is to Quiet as Shout is to ___', options: ['Loud', 'Angry', 'Fast', 'Short'], correct: 'Loud' },
                { prompt: 'Bee is to Hive as Bird is to ___', options: ['Nest', 'Sky', 'Branch', 'Wing'], correct: 'Nest' },
                { prompt: 'Moon is to Night as Sun is to ___', options: ['Day', 'Sky', 'Heat', 'Star'], correct: 'Day' },
            ],
        },
    },

    'Fraction Pizza': {
        grade: 'Grade 5',
        type: 'numeracy',
        description: 'Tap pizza slices to shade the fraction shown.',
        content: {
            rounds: [
                { totalSlices: 2, target: 1, targetLabel: '1/2' },
                { totalSlices: 4, target: 1, targetLabel: '1/4' },
                { totalSlices: 4, target: 2, targetLabel: '2/4' },
                { totalSlices: 4, target: 3, targetLabel: '3/4' },
                { totalSlices: 6, target: 1, targetLabel: '1/6' },
                { totalSlices: 6, target: 2, targetLabel: '2/6' },
                { totalSlices: 6, target: 4, targetLabel: '4/6' },
                { totalSlices: 6, target: 5, targetLabel: '5/6' },
                { totalSlices: 8, target: 1, targetLabel: '1/8' },
                { totalSlices: 8, target: 3, targetLabel: '3/8' },
                { totalSlices: 8, target: 5, targetLabel: '5/8' },
                { totalSlices: 8, target: 6, targetLabel: '6/8' },
                { totalSlices: 10, target: 2, targetLabel: '2/10' },
                { totalSlices: 10, target: 4, targetLabel: '4/10' },
                { totalSlices: 10, target: 7, targetLabel: '7/10' },
                { totalSlices: 10, target: 9, targetLabel: '9/10' },
                { totalSlices: 12, target: 5, targetLabel: '5/12' },
                { totalSlices: 12, target: 7, targetLabel: '7/12' },
                { totalSlices: 12, target: 9, targetLabel: '9/12' },
                { totalSlices: 12, target: 11, targetLabel: '11/12' },
            ],
        },
    },

    'Number Line Runner': {
        grade: 'Grade 5',
        type: 'numeracy',
        description: 'Click the number line to jump the correct number of spaces.',
        content: {
            rounds: [
                { start: 2, steps: 4, operation: '+', answer: 6, min: 0, max: 10 },
                { start: 9, steps: 3, operation: '-', answer: 6, min: 0, max: 10 },
                { start: 5, steps: 5, operation: '+', answer: 10, min: 0, max: 12 },
                { start: 8, steps: 6, operation: '-', answer: 2, min: 0, max: 10 },
                { start: 3, steps: 7, operation: '+', answer: 10, min: 0, max: 14 },
                { start: 12, steps: 4, operation: '-', answer: 8, min: 0, max: 14 },
                { start: 6, steps: 8, operation: '+', answer: 14, min: 0, max: 16 },
                { start: 15, steps: 5, operation: '-', answer: 10, min: 0, max: 16 },
                { start: 4, steps: 9, operation: '+', answer: 13, min: 0, max: 16 },
                { start: 14, steps: 6, operation: '-', answer: 8, min: 0, max: 16 },
                { start: 7, steps: 10, operation: '+', answer: 17, min: 0, max: 20 },
                { start: 18, steps: 7, operation: '-', answer: 11, min: 0, max: 20 },
                { start: 9, steps: 11, operation: '+', answer: 20, min: 0, max: 22 },
                { start: 20, steps: 9, operation: '-', answer: 11, min: 0, max: 22 },
                { start: 5, steps: 12, operation: '+', answer: 17, min: 0, max: 22 },
                { start: 22, steps: 10, operation: '-', answer: 12, min: 0, max: 24 },
                { start: 8, steps: 13, operation: '+', answer: 21, min: 0, max: 24 },
                { start: 24, steps: 11, operation: '-', answer: 13, min: 0, max: 26 },
                { start: 10, steps: 14, operation: '+', answer: 24, min: 0, max: 26 },
                { start: 26, steps: 12, operation: '-', answer: 14, min: 0, max: 28 },
            ],
        },
    },

    'Area Blocks': {
        grade: 'Grade 5',
        type: 'numeracy',
        description: 'Click grid squares to build a rectangle with the given number of rows and columns.',
        content: {
            rounds: [
                { rows: 2, cols: 3, target: 6, gridRows: 8, gridCols: 8 },
                { rows: 2, cols: 4, target: 8, gridRows: 8, gridCols: 8 },
                { rows: 3, cols: 3, target: 9, gridRows: 8, gridCols: 8 },
                { rows: 2, cols: 5, target: 10, gridRows: 8, gridCols: 8 },
                { rows: 3, cols: 4, target: 12, gridRows: 8, gridCols: 8 },
                { rows: 3, cols: 5, target: 15, gridRows: 8, gridCols: 8 },
                { rows: 4, cols: 4, target: 16, gridRows: 8, gridCols: 8 },
                { rows: 3, cols: 6, target: 18, gridRows: 8, gridCols: 8 },
                { rows: 4, cols: 5, target: 20, gridRows: 8, gridCols: 8 },
                { rows: 4, cols: 6, target: 24, gridRows: 8, gridCols: 8 },
                { rows: 5, cols: 5, target: 25, gridRows: 8, gridCols: 8 },
                { rows: 4, cols: 7, target: 28, gridRows: 8, gridCols: 8 },
                { rows: 5, cols: 6, target: 30, gridRows: 8, gridCols: 8 },
                { rows: 4, cols: 8, target: 32, gridRows: 8, gridCols: 8 },
                { rows: 5, cols: 7, target: 35, gridRows: 8, gridCols: 8 },
                { rows: 6, cols: 6, target: 36, gridRows: 8, gridCols: 8 },
                { rows: 5, cols: 8, target: 40, gridRows: 8, gridCols: 8 },
                { rows: 6, cols: 7, target: 42, gridRows: 8, gridCols: 8 },
                { rows: 6, cols: 8, target: 48, gridRows: 8, gridCols: 8 },
                { rows: 7, cols: 8, target: 56, gridRows: 8, gridCols: 8 },
            ],
        },
    },

    'Decimal Number Line': {
        grade: 'Grade 5',
        type: 'numeracy',
        description: 'Click the number line to jump the correct decimal distance.',
        content: {
            increment: 0.5,
            rounds: [
                { start: 1.0, jumpAmount: 1.0, operation: '+', answer: 2.0, min: 0, max: 5 },
                { start: 4.0, jumpAmount: 1.0, operation: '-', answer: 3.0, min: 0, max: 5 },
                { start: 1.5, jumpAmount: 1.5, operation: '+', answer: 3.0, min: 0, max: 6 },
                { start: 5.0, jumpAmount: 1.5, operation: '-', answer: 3.5, min: 0, max: 6 },
                { start: 2.0, jumpAmount: 2.0, operation: '+', answer: 4.0, min: 0, max: 7 },
                { start: 6.0, jumpAmount: 2.0, operation: '-', answer: 4.0, min: 0, max: 7 },
                { start: 2.5, jumpAmount: 2.5, operation: '+', answer: 5.0, min: 0, max: 8 },
                { start: 7.0, jumpAmount: 2.5, operation: '-', answer: 4.5, min: 0, max: 8 },
                { start: 3.0, jumpAmount: 3.0, operation: '+', answer: 6.0, min: 0, max: 9 },
                { start: 8.0, jumpAmount: 3.0, operation: '-', answer: 5.0, min: 0, max: 9 },
                { start: 3.5, jumpAmount: 3.5, operation: '+', answer: 7.0, min: 0, max: 10 },
                { start: 9.0, jumpAmount: 3.5, operation: '-', answer: 5.5, min: 0, max: 10 },
                { start: 4.0, jumpAmount: 4.0, operation: '+', answer: 8.0, min: 0, max: 10 },
                { start: 9.5, jumpAmount: 4.0, operation: '-', answer: 5.5, min: 0, max: 10 },
                { start: 1.0, jumpAmount: 4.5, operation: '+', answer: 5.5, min: 0, max: 10 },
                { start: 10.0, jumpAmount: 4.5, operation: '-', answer: 5.5, min: 0, max: 10 },
                { start: 2.0, jumpAmount: 5.0, operation: '+', answer: 7.0, min: 0, max: 12 },
                { start: 12.0, jumpAmount: 5.0, operation: '-', answer: 7.0, min: 0, max: 12 },
                { start: 3.0, jumpAmount: 5.5, operation: '+', answer: 8.5, min: 0, max: 12 },
                { start: 12.0, jumpAmount: 5.5, operation: '-', answer: 6.5, min: 0, max: 12 },
            ],
        },
    },

    // ===== GRADE 6 =====
    'Clue Detective': {
        grade: 'Grade 6',
        type: 'literacy',
        description: 'Click the words that reveal the meaning of the highlighted vocabulary word.',
        content: {
            rounds: [
                { words: ['The', 'artifact', 'was', 'invaluable', '—', 'extremely', 'valuable', 'and', 'impossible', 'to', 'replace', '.'], targetIndex: 3, clueRange: [5, 10] },
                { words: ['She', 'was', 'meticulous', ',', 'always', 'checking', 'every', 'detail', 'carefully', 'before', 'submitting', 'her', 'work', '.'], targetIndex: 2, clueRange: [4, 8] },
                { words: ['The', 'weather', 'was', 'turbulent', ',', 'with', 'strong', 'winds', 'and', 'heavy', 'rain', 'battering', 'the', 'coast', '.'], targetIndex: 3, clueRange: [5, 10] },
                { words: ['The', 'detective', 'was', 'diligent', ',', 'carefully', 'examining', 'every', 'piece', 'of', 'evidence', 'before', 'drawing', 'conclusions', '.'], targetIndex: 3, clueRange: [5, 10] },
                { words: ['The', 'old', 'house', 'looked', 'dilapidated', ',', 'with', 'broken', 'windows', 'and', 'a', 'collapsing', 'roof', '.'], targetIndex: 4, clueRange: [6, 12] },
                { words: ['Her', 'explanation', 'was', 'ambiguous', ',', 'leaving', 'the', 'class', 'confused', 'about', 'what', 'she', 'truly', 'meant', '.'], targetIndex: 3, clueRange: [5, 13] },
                { words: ['The', 'magician\'s', 'trick', 'was', 'baffling', ',', 'and', 'no', 'one', 'in', 'the', 'audience', 'could', 'explain', 'how', 'it', 'worked', '.'], targetIndex: 4, clueRange: [7, 16] },
                { words: ['The', 'soup', 'tasted', 'bland', ',', 'lacking', 'any', 'spices', 'or', 'seasoning', 'to', 'give', 'it', 'flavor', '.'], targetIndex: 3, clueRange: [5, 9] },
                { words: ['The', 'champion\'s', 'victory', 'was', 'inevitable', ',', 'since', 'no', 'other', 'team', 'could', 'match', 'her', 'skill', 'and', 'speed', '.'], targetIndex: 4, clueRange: [6, 15] },
                { words: ['The', 'old', 'man\'s', 'memory', 'was', 'fading', ',', 'and', 'he', 'often', 'forgot', 'where', 'he', 'placed', 'his', 'keys', '.'], targetIndex: 5, clueRange: [7, 15] },
                { words: ['The', 'crowd', 'was', 'jubilant', ',', 'cheering', 'loudly', 'and', 'celebrating', 'the', 'team\'s', 'amazing', 'victory', '.'], targetIndex: 3, clueRange: [5, 12] },
                { words: ['His', 'argument', 'was', 'persuasive', ',', 'convincing', 'even', 'the', 'most', 'skeptical', 'members', 'of', 'the', 'audience', '.'], targetIndex: 3, clueRange: [5, 13] },
                { words: ['The', 'ancient', 'ruins', 'were', 'desolate', ',', 'with', 'no', 'sign', 'of', 'life', 'for', 'miles', 'around', '.'], targetIndex: 4, clueRange: [6, 13] },
                { words: ['The', 'new', 'employee', 'was', 'diligent', ',', 'arriving', 'early', 'and', 'staying', 'late', 'to', 'finish', 'every', 'task', '.'], targetIndex: 4, clueRange: [6, 14] },
                { words: ['The', 'scientist\'s', 'discovery', 'was', 'groundbreaking', ',', 'changing', 'how', 'people', 'understood', 'the', 'universe', 'forever', '.'], targetIndex: 4, clueRange: [6, 12] },
                { words: ['The', 'politician\'s', 'speech', 'was', 'eloquent', ',', 'filled', 'with', 'powerful', 'words', 'that', 'moved', 'the', 'entire', 'crowd', '.'], targetIndex: 4, clueRange: [6, 14] },
                { words: ['The', 'abandoned', 'building', 'was', 'derelict', ',', 'its', 'walls', 'crumbling', 'and', 'windows', 'shattered', 'by', 'years', 'of', 'neglect', '.'], targetIndex: 4, clueRange: [6, 15] },
                { words: ['The', 'professor\'s', 'lecture', 'was', 'tedious', ',', 'dragging', 'on', 'for', 'hours', 'without', 'a', 'single', 'interesting', 'point', '.'], targetIndex: 4, clueRange: [6, 14] },
                { words: ['The', 'athlete\'s', 'performance', 'was', 'exceptional', ',', 'breaking', 'three', 'records', 'in', 'a', 'single', 'afternoon', '.'], targetIndex: 4, clueRange: [6, 12] },
                { words: ['The', 'company\'s', 'decision', 'was', 'controversial', ',', 'sparking', 'heated', 'debate', 'among', 'employees', 'and', 'shareholders', 'alike', '.'], targetIndex: 4, clueRange: [6, 13] },
            ],
        },
    },

    'Word Web Builder': {
        grade: 'Grade 6',
        type: 'literacy',
        description: 'Drag the words that relate to the central concept into the web.',
        content: {
            centralWord: 'OCEAN',
            correctWords: ['Wave', 'Coral', 'Tide', 'Current', 'Reef', 'Shark', 'Plankton', 'Shore', 'Saltwater', 'Whale'],
            distractorWords: ['Mountain', 'Desert', 'Cactus', 'Volcano', 'Forest', 'Glacier', 'Meadow', 'Canyon', 'Prairie', 'Tundra'],
        },
    },

    'Sequence the Story': {
        grade: 'Grade 6',
        type: 'literacy',
        description: 'Drag the story events into the correct chronological order.',
        content: {
            rounds: [
                { correct: ['Woke up', 'Ate breakfast', 'Brushed teeth', 'Left for school'], scrambled: ['Brushed teeth', 'Left for school', 'Woke up', 'Ate breakfast'] },
                { correct: ['Planted a seed', 'Watered it daily', 'Seedling sprouted', 'Flower bloomed'], scrambled: ['Flower bloomed', 'Planted a seed', 'Seedling sprouted', 'Watered it daily'] },
                { correct: ['Mixed the batter', 'Poured it in the pan', 'Baked it in the oven', 'Let it cool'], scrambled: ['Let it cool', 'Baked it in the oven', 'Mixed the batter', 'Poured it in the pan'] },
                { correct: ['Packed the suitcase', 'Drove to the airport', 'Boarded the plane', 'Landed in Paris'], scrambled: ['Boarded the plane', 'Packed the suitcase', 'Landed in Paris', 'Drove to the airport'] },
                { correct: ['Found an old map', 'Followed the trail', 'Discovered a cave', 'Found hidden treasure'], scrambled: ['Discovered a cave', 'Found hidden treasure', 'Found an old map', 'Followed the trail'] },
                { correct: ['Studied for the test', 'Took the exam', 'Waited for results', 'Received a high score'], scrambled: ['Waited for results', 'Studied for the test', 'Received a high score', 'Took the exam'] },
                { correct: ['Caught the fish', 'Cleaned it', 'Cooked it', 'Ate dinner'], scrambled: ['Cooked it', 'Ate dinner', 'Caught the fish', 'Cleaned it'] },
                { correct: ['Wrote the first draft', 'Revised the story', 'Asked a friend to read it', 'Submitted the final version'], scrambled: ['Asked a friend to read it', 'Submitted the final version', 'Wrote the first draft', 'Revised the story'] },
                { correct: ['Trained every day', 'Entered the competition', 'Ran the race', 'Won first place'], scrambled: ['Ran the race', 'Trained every day', 'Won first place', 'Entered the competition'] },
                { correct: ['Collected rain water', 'Filtered the water', 'Boiled it', 'Drank it safely'], scrambled: ['Boiled it', 'Collected rain water', 'Drank it safely', 'Filtered the water'] },
                { correct: ['Gathered building blocks', 'Sketched a design', 'Built the model', 'Displayed it in class'], scrambled: ['Built the model', 'Gathered building blocks', 'Displayed it in class', 'Sketched a design'] },
                { correct: ['Saved money each month', 'Opened a bank account', 'Deposited the savings', 'Bought a new bike'], scrambled: ['Deposited the savings', 'Bought a new bike', 'Saved money each month', 'Opened a bank account'] },
                { correct: ['Noticed a strange sound', 'Investigated the noise', 'Found a stray cat', 'Brought it home'], scrambled: ['Found a stray cat', 'Noticed a strange sound', 'Brought it home', 'Investigated the noise'] },
                { correct: ['Set up the tent', 'Started a campfire', 'Cooked marshmallows', 'Told stories under the stars'], scrambled: ['Cooked marshmallows', 'Set up the tent', 'Told stories under the stars', 'Started a campfire'] },
                { correct: ['Signed up for the club', 'Attended the first meeting', 'Practiced the routine', 'Performed on stage'], scrambled: ['Practiced the routine', 'Signed up for the club', 'Performed on stage', 'Attended the first meeting'] },
                { correct: ['Watered the garden', 'Pulled the weeds', 'Harvested vegetables', 'Cooked a fresh meal'], scrambled: ['Harvested vegetables', 'Watered the garden', 'Cooked a fresh meal', 'Pulled the weeds'] },
                { correct: ['Researched the topic', 'Made an outline', 'Wrote the report', 'Presented it to the class'], scrambled: ['Wrote the report', 'Researched the topic', 'Presented it to the class', 'Made an outline'] },
                { correct: ['Boarded the ship', 'Sailed across the sea', 'Spotted an island', 'Explored the shore'], scrambled: ['Spotted an island', 'Boarded the ship', 'Explored the shore', 'Sailed across the sea'] },
                { correct: ['Repaired the broken toy', 'Tested it', 'Wrapped it as a gift', 'Gave it to a friend'], scrambled: ['Wrapped it as a gift', 'Repaired the broken toy', 'Gave it to a friend', 'Tested it'] },
                { correct: ['Practiced the song', 'Auditioned for the choir', 'Was accepted', 'Sang at the concert'], scrambled: ['Was accepted', 'Practiced the song', 'Sang at the concert', 'Auditioned for the choir'] },
            ],
        },
    },

    'Idiom Match': {
        grade: 'Grade 6',
        type: 'literacy',
        description: 'Drag each idiom on the left to its true meaning on the right.',
        content: {
            pairs: [
                { word: 'Break the ice', match: 'Start a conversation' },
                { word: 'Piece of cake', match: 'Very easy' },
                { word: 'Under the weather', match: 'Feeling sick' },
                { word: 'Hit the books', match: 'Study hard' },
                { word: 'Once in a blue moon', match: 'Rarely happens' },
                { word: 'Costs an arm and a leg', match: 'Very expensive' },
                { word: 'Let the cat out of the bag', match: 'Reveal a secret' },
                { word: 'Bite the bullet', match: 'Face something difficult' },
                { word: 'Burning the midnight oil', match: 'Working late at night' },
                { word: 'Spill the beans', match: 'Tell a secret' },
                { word: 'On the ball', match: 'Alert and competent' },
                { word: 'Speak of the devil', match: 'The person just mentioned appears' },
                { word: 'Cut corners', match: 'Do something poorly to save time' },
                { word: 'Hit the nail on the head', match: 'Say exactly the right thing' },
                { word: 'Miss the boat', match: 'Miss an opportunity' },
                { word: 'A blessing in disguise', match: 'A good thing that seemed bad at first' },
                { word: 'Get cold feet', match: 'Become nervous before doing something' },
                { word: 'Pull someone\'s leg', match: 'Joke with someone' },
                { word: 'See eye to eye', match: 'Agree completely' },
                { word: 'Beat around the bush', match: 'Avoid saying something directly' },
            ],
        },
    },

    'Balance Scale': {
        grade: 'Grade 6',
        type: 'numeracy',
        description: 'Drag weights onto the right side until the scale balances.',
        content: {
            rounds: [
                { leftValue: 9, weights: [4, 5, 2, 6, 3] },
                { leftValue: 10, weights: [3, 7, 2, 5, 4] },
                { leftValue: 11, weights: [4, 7, 2, 6, 3] },
                { leftValue: 12, weights: [5, 7, 4, 3, 6] },
                { leftValue: 13, weights: [6, 7, 3, 5, 4] },
                { leftValue: 14, weights: [6, 8, 3, 5, 4] },
                { leftValue: 15, weights: [8, 7, 3, 5, 2] },
                { leftValue: 16, weights: [9, 7, 4, 6, 3] },
                { leftValue: 17, weights: [9, 8, 4, 6, 3] },
                { leftValue: 18, weights: [10, 8, 4, 6, 3] },
                { leftValue: 19, weights: [11, 8, 5, 7, 3] },
                { leftValue: 20, weights: [12, 8, 5, 7, 3] },
                { leftValue: 21, weights: [13, 8, 5, 7, 3] },
                { leftValue: 22, weights: [14, 8, 5, 7, 3] },
                { leftValue: 23, weights: [15, 8, 5, 7, 3] },
                { leftValue: 24, weights: [16, 8, 5, 7, 3] },
                { leftValue: 25, weights: [17, 8, 5, 7, 3] },
                { leftValue: 26, weights: [18, 8, 5, 7, 3] },
                { leftValue: 28, weights: [20, 8, 5, 7, 3] },
                { leftValue: 30, weights: [22, 8, 5, 7, 3] },
            ],
        },
    },

    'Graph Builder': {
        grade: 'Grade 6',
        type: 'numeracy',
        description: 'Click each bar to build it up to match the data, then answer a quick question about your graph.',
        content: {
            rounds: [
                { title: 'Favorite Fruits Survey', maxValue: 10, categories: [{ label: 'Apple', target: 4 }, { label: 'Banana', target: 7 }, { label: 'Grape', target: 3 }], question: 'Which fruit got the most votes?', answer: 'Banana' },
                { title: 'Pets Owned by Classmates', maxValue: 8, categories: [{ label: 'Dog', target: 6 }, { label: 'Cat', target: 5 }, { label: 'Fish', target: 2 }], question: 'Which pet is the least common?', answer: 'Fish' },
                { title: 'Favorite Sports', maxValue: 12, categories: [{ label: 'Basketball', target: 8 }, { label: 'Soccer', target: 10 }, { label: 'Tennis', target: 4 }], question: 'Which sport is most popular?', answer: 'Soccer' },
                { title: 'Ice Cream Flavors', maxValue: 10, categories: [{ label: 'Vanilla', target: 5 }, { label: 'Chocolate', target: 9 }, { label: 'Strawberry', target: 3 }], question: 'Which flavor is most popular?', answer: 'Chocolate' },
                { title: 'Weekly Rainfall (mm)', maxValue: 10, categories: [{ label: 'Mon', target: 3 }, { label: 'Tue', target: 7 }, { label: 'Wed', target: 5 }], question: 'Which day had the most rain?', answer: 'Tue' },
                { title: 'Books Read This Month', maxValue: 8, categories: [{ label: 'Fiction', target: 6 }, { label: 'Non-Fiction', target: 4 }, { label: 'Comics', target: 7 }], question: 'Which category had the most books?', answer: 'Comics' },
                { title: 'Favorite Subjects', maxValue: 10, categories: [{ label: 'Math', target: 7 }, { label: 'Science', target: 9 }, { label: 'Art', target: 5 }], question: 'Which subject is most popular?', answer: 'Science' },
                { title: 'Classroom Pets Wanted', maxValue: 8, categories: [{ label: 'Hamster', target: 3 }, { label: 'Turtle', target: 6 }, { label: 'Bird', target: 4 }], question: 'Which pet is most wanted?', answer: 'Turtle' },
                { title: 'Vehicles in the Parking Lot', maxValue: 12, categories: [{ label: 'Cars', target: 10 }, { label: 'Trucks', target: 6 }, { label: 'Motorcycles', target: 3 }], question: 'Which vehicle type is most common?', answer: 'Cars' },
                { title: 'Favorite Colors', maxValue: 10, categories: [{ label: 'Blue', target: 8 }, { label: 'Red', target: 5 }, { label: 'Green', target: 6 }], question: 'Which color is most popular?', answer: 'Blue' },
                { title: 'Snacks Sold', maxValue: 12, categories: [{ label: 'Chips', target: 9 }, { label: 'Cookies', target: 11 }, { label: 'Fruit', target: 6 }], question: 'Which snack sold the most?', answer: 'Cookies' },
                { title: 'Hours Spent on Homework', maxValue: 8, categories: [{ label: 'Mon', target: 5 }, { label: 'Wed', target: 7 }, { label: 'Fri', target: 3 }], question: 'Which day had the most homework?', answer: 'Wed' },
                { title: 'Favorite Music Genres', maxValue: 10, categories: [{ label: 'Pop', target: 9 }, { label: 'Rock', target: 6 }, { label: 'Jazz', target: 4 }], question: 'Which genre is most popular?', answer: 'Pop' },
                { title: 'Recycling Collected (kg)', maxValue: 12, categories: [{ label: 'Paper', target: 10 }, { label: 'Plastic', target: 7 }, { label: 'Glass', target: 5 }], question: 'Which material had the most collected?', answer: 'Paper' },
                { title: 'Favorite Board Games', maxValue: 10, categories: [{ label: 'Chess', target: 6 }, { label: 'Monopoly', target: 8 }, { label: 'Checkers', target: 4 }], question: 'Which game is most popular?', answer: 'Monopoly' },
                { title: 'Students per Club', maxValue: 12, categories: [{ label: 'Art Club', target: 7 }, { label: 'Science Club', target: 11 }, { label: 'Music Club', target: 5 }], question: 'Which club has the most students?', answer: 'Science Club' },
                { title: 'Daily Steps (thousands)', maxValue: 10, categories: [{ label: 'Mon', target: 6 }, { label: 'Tue', target: 9 }, { label: 'Wed', target: 4 }], question: 'Which day had the most steps?', answer: 'Tue' },
                { title: 'Favorite Season', maxValue: 10, categories: [{ label: 'Summer', target: 8 }, { label: 'Winter', target: 5 }, { label: 'Spring', target: 7 }], question: 'Which season is most popular?', answer: 'Summer' },
                { title: 'Fundraiser Earnings ($100s)', maxValue: 12, categories: [{ label: 'Grade A', target: 9 }, { label: 'Grade B', target: 12 }, { label: 'Grade C', target: 6 }], question: 'Which grade raised the most?', answer: 'Grade B' },
                { title: 'Video Game Genres', maxValue: 10, categories: [{ label: 'Action', target: 9 }, { label: 'Puzzle', target: 5 }, { label: 'Adventure', target: 7 }], question: 'Which genre is most popular?', answer: 'Action' },
            ],
        },
    },

    'Coordinate Plane Treasure Hunt': {
        grade: 'Grade 6',
        type: 'numeracy',
        description: 'Click the exact point on the grid that matches the given coordinates.',
        content: {
            rounds: [
                { x: 2, y: 3, rangeMin: 0, rangeMax: 10 },
                { x: 5, y: 1, rangeMin: 0, rangeMax: 10 },
                { x: 7, y: 4, rangeMin: 0, rangeMax: 10 },
                { x: 1, y: 8, rangeMin: 0, rangeMax: 10 },
                { x: 9, y: 2, rangeMin: 0, rangeMax: 10 },
                { x: 4, y: 6, rangeMin: 0, rangeMax: 10 },
                { x: 6, y: 9, rangeMin: 0, rangeMax: 10 },
                { x: 3, y: 3, rangeMin: 0, rangeMax: 10 },
                { x: 8, y: 7, rangeMin: 0, rangeMax: 10 },
                { x: 0, y: 5, rangeMin: 0, rangeMax: 10 },
                { x: -2, y: 3, rangeMin: -10, rangeMax: 10 },
                { x: 4, y: -5, rangeMin: -10, rangeMax: 10 },
                { x: -6, y: -2, rangeMin: -10, rangeMax: 10 },
                { x: -3, y: 7, rangeMin: -10, rangeMax: 10 },
                { x: 7, y: -4, rangeMin: -10, rangeMax: 10 },
                { x: -8, y: 8, rangeMin: -10, rangeMax: 10 },
                { x: 5, y: -9, rangeMin: -10, rangeMax: 10 },
                { x: -5, y: -5, rangeMin: -10, rangeMax: 10 },
                { x: 9, y: -3, rangeMin: -10, rangeMax: 10 },
                { x: -7, y: 6, rangeMin: -10, rangeMax: 10 },
            ],
        },
    },

    'Percent Bar Builder': {
        grade: 'Grade 6',
        type: 'numeracy',
        description: 'Click each bar to build it up to the correct percentage, then answer a quick question.',
        content: {
            rounds: [
                { title: 'Class Survey: Favorite Subject (%)', categories: [{ label: 'Math', target: 40 }, { label: 'Science', target: 35 }, { label: 'Art', target: 25 }], question: 'Which subject got the highest percentage?', answer: 'Math' },
                { title: 'Recycling Breakdown (%)', categories: [{ label: 'Paper', target: 50 }, { label: 'Plastic', target: 30 }, { label: 'Glass', target: 20 }], question: 'Which material makes up the smallest percentage?', answer: 'Glass' },
                { title: 'Weekly Screen Time (%)', categories: [{ label: 'Games', target: 45 }, { label: 'Videos', target: 35 }, { label: 'Reading', target: 20 }], question: 'Which activity takes the most time?', answer: 'Games' },
                { title: 'School Lunch Choices (%)', categories: [{ label: 'Pizza', target: 55 }, { label: 'Salad', target: 20 }, { label: 'Pasta', target: 25 }], question: 'Which lunch is least popular?', answer: 'Salad' },
                { title: 'Sports Participation (%)', categories: [{ label: 'Basketball', target: 40 }, { label: 'Soccer', target: 45 }, { label: 'Swimming', target: 15 }], question: 'Which sport has the most participants?', answer: 'Soccer' },
                { title: 'Energy Sources (%)', categories: [{ label: 'Solar', target: 30 }, { label: 'Wind', target: 25 }, { label: 'Fossil', target: 45 }], question: 'Which source is used the most?', answer: 'Fossil' },
                { title: 'Pet Ownership (%)', categories: [{ label: 'Dogs', target: 50 }, { label: 'Cats', target: 35 }, { label: 'Fish', target: 15 }], question: 'Which pet is most common?', answer: 'Dogs' },
                { title: 'Book Genre Preference (%)', categories: [{ label: 'Fantasy', target: 40 }, { label: 'Mystery', target: 30 }, { label: 'Nonfiction', target: 30 }], question: 'Which genre is the top choice?', answer: 'Fantasy' },
                { title: 'Weather This Month (%)', categories: [{ label: 'Sunny', target: 60 }, { label: 'Rainy', target: 25 }, { label: 'Cloudy', target: 15 }], question: 'What was the most common weather?', answer: 'Sunny' },
                { title: 'Transportation to School (%)', categories: [{ label: 'Walk', target: 35 }, { label: 'Bus', target: 45 }, { label: 'Car', target: 20 }], question: 'How do most students get to school?', answer: 'Bus' },
                { title: 'Fruit Sales (%)', categories: [{ label: 'Apples', target: 30 }, { label: 'Bananas', target: 45 }, { label: 'Oranges', target: 25 }], question: 'Which fruit sold the most?', answer: 'Bananas' },
                { title: 'Music Streaming (%)', categories: [{ label: 'Pop', target: 50 }, { label: 'Rock', target: 20 }, { label: 'Hip-Hop', target: 30 }], question: 'Which genre is streamed most?', answer: 'Pop' },
                { title: 'Water Usage at Home (%)', categories: [{ label: 'Bathroom', target: 60 }, { label: 'Kitchen', target: 25 }, { label: 'Laundry', target: 15 }], question: 'Where is most water used?', answer: 'Bathroom' },
                { title: 'Test Score Distribution (%)', categories: [{ label: 'A', target: 35 }, { label: 'B', target: 45 }, { label: 'C', target: 20 }], question: 'Which grade was most common?', answer: 'B' },
                { title: 'Volunteer Hours (%)', categories: [{ label: 'Cleanup', target: 40 }, { label: 'Tutoring', target: 35 }, { label: 'Fundraising', target: 25 }], question: 'Which activity had the most hours?', answer: 'Cleanup' },
                { title: 'Class Trip Votes (%)', categories: [{ label: 'Museum', target: 30 }, { label: 'Zoo', target: 50 }, { label: 'Beach', target: 20 }], question: 'Where do most students want to go?', answer: 'Zoo' },
                { title: 'Daily Diet Breakdown (%)', categories: [{ label: 'Protein', target: 30 }, { label: 'Carbs', target: 50 }, { label: 'Fat', target: 20 }], question: 'Which makes up the largest share?', answer: 'Carbs' },
                { title: 'Device Usage (%)', categories: [{ label: 'Phone', target: 55 }, { label: 'Tablet', target: 25 }, { label: 'Computer', target: 20 }], question: 'Which device is used most?', answer: 'Phone' },
                { title: 'Garden Plants (%)', categories: [{ label: 'Flowers', target: 45 }, { label: 'Vegetables', target: 40 }, { label: 'Herbs', target: 15 }], question: 'Which plant type takes up the most space?', answer: 'Flowers' },
                { title: 'Weekend Chores (%)', categories: [{ label: 'Cleaning', target: 50 }, { label: 'Cooking', target: 30 }, { label: 'Laundry', target: 20 }], question: 'Which chore takes the most time?', answer: 'Cleaning' },
            ],
        },
    },
};

export default gameDefinitions;
