<?php

namespace App\Helpers;

use Illuminate\Http\Response;
use Illuminate\Support\Facades\Response as ResponseFacade;

class ExportHelper
{
    /**
     * Generate CSV export from array data.
     */
    public static function generateCsv(array $data, array $headers = [], string $filename = null): Response
    {
        if (empty($data)) {
            return ResponseFacade::make('No data available for export.', 200, [
                'Content-Type' => 'text/plain',
            ]);
        }

        $filename = $filename ?? 'export_' . now()->format('Y-m-d_His') . '.csv';

        // Determine headers from the first row if not provided
        if (empty($headers)) {
            $headers = array_keys($data[0]);
        }

        $callback = function () use ($data, $headers) {
            $file = fopen('php://output', 'w');

            // Add BOM for UTF-8
            fputs($file, "\xEF\xBB\xBF");

            // Add headers
            fputcsv($file, $headers);

            // Add data rows
            foreach ($data as $row) {
                $rowData = [];
                foreach ($headers as $header) {
                    $rowData[] = $row[$header] ?? '';
                }
                fputcsv($file, $rowData);
            }

            fclose($file);
        };

        return ResponseFacade::stream($callback, 200, [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }

    /**
     * Generate Excel-style export using CSV format.
     * For full Excel support, use Laravel Excel package.
     */
    public static function generateExcel(array $data, array $headers = [], string $filename = null): Response
    {
        // For now, we use CSV format with Excel-friendly settings
        // To get full Excel support, install: composer require maatwebsite/excel
        $filename = $filename ?? 'export_' . now()->format('Y-m-d_His') . '.xlsx';

        // Since we don't have the Excel package installed, we'll generate a CSV
        // that Excel can open (use UTF-8 with BOM)
        return self::generateCsv($data, $headers, $filename);
    }

    /**
     * Generate a print-friendly HTML version of the data.
     */
    public static function generatePrint(array $data, array $headers = [], string $title = 'Report'): string
    {
        if (empty($data)) {
            return '<p>No data available for this report.</p>';
        }

        if (empty($headers)) {
            $headers = array_keys($data[0]);
        }

        $html = '<html><head><title>' . htmlspecialchars($title) . '</title>';
        $html .= '<style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #4B5563; color: white; padding: 10px; text-align: left; }
            td { padding: 8px 10px; border-bottom: 1px solid #ddd; }
            tr:nth-child(even) { background-color: #f9f9f9; }
            .footer { margin-top: 20px; color: #666; font-size: 12px; }
            @media print { .no-print { display: none; } }
        </style>';
        $html .= '</head><body>';
        $html .= '<h1>' . htmlspecialchars($title) . '</h1>';
        $html .= '<p>Generated: ' . now()->format('Y-m-d H:i') . '</p>';
        $html .= '<table>';
        $html .= '<thead><tr>';
        foreach ($headers as $header) {
            $html .= '<th>' . htmlspecialchars(str_replace('_', ' ', ucwords($header))) . '</th>';
        }
        $html .= '</tr></thead>';
        $html .= '<tbody>';
        foreach ($data as $row) {
            $html .= '<tr>';
            foreach ($headers as $header) {
                $value = $row[$header] ?? '';
                $html .= '<td>' . htmlspecialchars($value) . '</td>';
            }
            $html .= '</tr>';
        }
        $html .= '</tbody></table>';
        $html .= '<div class="footer">Generated by StudyNest</div>';
        $html .= '</body></html>';

        return $html;
    }

    /**
     * Format data for export.
     */
    public static function formatDataForExport(array $data, array $headers = []): array
    {
        if (empty($data)) {
            return [];
        }

        if (empty($headers)) {
            return $data;
        }

        $formatted = [];
        foreach ($data as $row) {
            $formattedRow = [];
            foreach ($headers as $header) {
                $formattedRow[$header] = $row[$header] ?? '';
            }
            $formatted[] = $formattedRow;
        }

        return $formatted;
    }
}
